In [3]:
import numpy as np
import time

In [4]:
arr = np.array([1,2,3,4,5])
print(arr,type(arr))


[1 2 3 4 5] <class 'numpy.ndarray'>


In [5]:
pylist = [1,2,3,4,5]
arr1 = np.array(pylist)
print(pylist,type(pylist))
print(arr1,type(arr1))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [6]:
size = 10000000
#python list 
py_list = list(range(size))
start =time.time()
sq_list = [x**2 for x in py_list] 
end = time.time()
print(f"python list time is : {end - start} second")

#NumPy 
np_arr= np.array(py_list)
start= time.time()
#vectorization
sq_arr = np_arr**2
end = time.time()
print(f"python NumPy time is : {end - start} second")

python list time is : 0.9593274593353271 second
python NumPy time is : 0.0301058292388916 second


In [7]:
#memory
import sys
print(f"python list size: {sys.getsizeof(py_list)*len(py_list)} bytes")
print(f"python NumPy size: {np_arr.nbytes} bytes")

python list size: 800000560000000 bytes
python NumPy size: 80000000 bytes


In [8]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)
print(arr_2d.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [9]:
arr  = np.zeros((2,3),dtype="int64")
print(arr,arr.shape)

[[0 0 0]
 [0 0 0]] (2, 3)


In [10]:
arr = np.full((5,6),45)
print(arr,arr.shape)

[[45 45 45 45 45 45]
 [45 45 45 45 45 45]
 [45 45 45 45 45 45]
 [45 45 45 45 45 45]
 [45 45 45 45 45 45]] (5, 6)


In [11]:
#identity matrix
arr4 = np.eye(3)
print(arr4,arr4.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)


In [12]:
arr5 = np.arange(1,11)
print(arr5,arr5.shape)

[ 1  2  3  4  5  6  7  8  9 10] (10,)


In [13]:
# for create even space array
arr6 = np.linspace(0,100,4)
print(arr6,arr6.shape)

[  0.          33.33333333  66.66666667 100.        ] (4,)


In [14]:
# Properties 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)
float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [18]:
#operation on array
arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)
reshape_arr= arr.reshape(3,2)
print(reshape_arr,reshape_arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [19]:
flattend = arr.flatten()
print(flattend,flattend.shape)

[1 2 3 4 5 6] (6,)


In [25]:
arr = np.array([1,2,3,4,5])
idx = [0,2,3]
print(arr[idx])
print(arr[arr>3])
print(arr[arr%2==0])

[1 3 4]
[4 5]
[2 4]


In [28]:
# Slicing 
arr = np.array([1,2,3,4,5,6,7])
print(arr[0:5:2])

[1 3 5]


In [30]:
#copy as view
sub_arr=arr[1:5]
print(sub_arr)


[2 3 4 5]


In [33]:
#Complex No
arr = np.array([3+5j])
arr1 = np.array([4+7j])
print(arr+arr1,arr.dtype)




[7.+12.j] complex128


In [34]:
#Data type
arr = np.array(["swapnil",{1,2,3},3.14])
print(arr,arr.dtype)

['swapnil' {1, 2, 3} 3.14] object


Multidimensional array

In [35]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print(np.sum(arr2d))
sum_of_cols = np.sum(arr2d,axis = 0)
print(sum_of_cols)
sum_of_rows = np.sum(arr2d, axis=1) 
print(sum_of_rows)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]


In [36]:
print(arr2d[0:2,1:2])

[[2]
 [5]]


3 D array

In [37]:
arr = np.array([[[1,2],[3,4],[5,6]],[[7,8],[8,9],[2,5]]])
print(arr,arr.dtype)

[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [8 9]
  [2 5]]] int64


In [41]:
print(arr[1,2,1])
#slicing
print(arr[:,0,:])

5
[[1 2]
 [7 8]]


In [43]:
# vecotrisation
arr = np.array([1,2,3,4,5])
print(arr**2)
print(arr+50)


[ 1  4  9 16 25]
[51 52 53 54 55]


In [48]:
#Normalize
arr = np.array([[1,2],[3,4]])
print(arr)
print(np.mean(arr))
print(np.std(arr))


[[1 2]
 [3 4]]
2.5
1.118033988749895


Mathematical function

In [69]:
# aggregation
arr = np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.argmax(arr))
print(np.argmin(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))
print(np.sqrt(arr))
print(np.square(arr))
print(np.pow(arr,5))

# log
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

print(np.round(3.14666))
print(np.ceil(3.14666))
print(np.trunc(3.14666))

arr1 = np.array([1,2,3,4,5,8.9,-4,-9,-2,6,7,10])
print(np.abs(arr1))









15
120
4
0
5
1
3.0
1.4142135623730951
3.0
2.0
[1.         1.41421356 1.73205081 2.         2.23606798]
[ 1  4  9 16 25]
[   1   32  243 1024 3125]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
3.0
4.0
3.0
[ 1.   2.   3.   4.   5.   8.9  4.   9.   2.   6.   7.  10. ]
